### ISSUE TITLE
Allow to disable particular instance check types

### ISSUE THREAD

**Issue by krystian-panek-wttech** [wttech/aemc#165]
e.g when there is some heavy AEM override applied e.g login page may not work typically
then our AEMC health check may not work or be available.

to prevent such a situation from happening some checks should be skippable or more customizable:

```yml
instance:
  check:
    login_page:
      skip: true
```

extend [CheckSpec](https://github.com/wttech/aemc/blob/872edcf3ad953b49ce4279cee24fdf9a46b2d440/pkg/check.go#L39) to implement it
