### ISSUE TITLE
More detailed components checking

### ISSUE THREAD

**Issue by krystian-panek-wttech** [wttech/aemc#230]
AC

1. By default expect that PIDs of own components need to be in `active` state - right now we are checking if there are some components with `unsatisfied (reference)` state
2. Allow to specify corner cases - a list of components that may have different state or states like `no config`
3. Write down differences in states of components

New version of component check config:

```yml
    # OSGi components state tracking
    component_stable:
      skip: false

      pids:
        include: ['com.acme.aem.core.*']
        exclude: []
        match:
          disabled: ['com.acme.aem.core.tmp.*']
          no_config: ['com.acme.aem.core.config.*']
          unsatisfied_reference: ['*_publish*:com.acme.aem.core.workflow.rollout.*Step']
          satisfied: ['com.acme.aem.core.dependent.*']
```
